version: '3.9'

services:
  node:
    build:
      context: ./
      dockerfile: NodeDockerfile
    deploy:
      replicas: 3
  supervisor:
    build:
      context: ./
      dockerfile: SupervisorDockerfile
    deploy:
      replicas: 1